FROM node:20.5.1
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

# O comando `RUN npm install -g json-server` é usado em um arquivo Dockerfile para instalar globalmente 
# o pacote `json-server` dentro da imagem Docker
RUN npm install -g json-server
COPY . .
EXPOSE 5173
EXPOSE 3000
CMD ["sh", "-c", "npm run dev -- --host & json-server --watch eventos.json"]


# Este comando CMD ["sh", "-c", "npm run dev -- --host & json-server --watch eventos.json"]
# é usado em um ambiente Docker para executar dois processos simultaneamente: um servidor de
# desenvolvimento de Node.js (con npm run dev) 
# e um servidor JSON local (con json-server).

# CMD : Este é um comando do Docker que define o comando predeterminado que será executado quando o 
# contêiner for iniciado. Neste caso, o comando está executando um script de shell ( sh).

# ["sh", "-c", ...] : Isso indica que você está usando o shell do Unix ( sh) para executar uma série de comandos.
# O parâmetro -c diz ao shell que executa a cadeia que segue como um comando solo.

# npm execute dev -- --host :
# npm run dev: Executa o script chamado dev definido no arquivo package.json. Normalmente, em 
# ambientes Node.js, isso se refere à execução de um servidor de desenvolvimento para o aplicativo.
# --host: Este argumento se passa no script dev, que na maioria dos casos indica que o servidor 
# deverá estar disponível externamente, não apenas em localhost. Aceite conexões de qualquer direção IP.
# & : Este símbolo em um script de shell executa o comando anterior no segundo plano. Isso significa 
# que o servidor de desenvolvimento ( npm run dev) continuará sendo executado em segundo plano, 
# permitindo que o comando seguinte seja executado em paralelo.

# json-server --watch eventos.json :
# json-server: Este é um pacote de Node.js que é utilizado para criar uma API REST completa
# --watch eventos.json: Este parâmetrojson-server de eventos.jsone geral


# Observação : Explicação pesquisada sobre cada comando e sua utlização com a ajuda do chatGPT e outros
# sites de pesquisas como: https://stackoverflow.com/